---
- name: install dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh

- name: clone antigen for users
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: yes
  become_user: '{{ item.username }}'
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/zsh-users/antigen.git ~/.antigen'
  args:
    creates: '~{{ item.username }}/.antigen'
  when: (item.antigen_libraries is defined) or (item.antigen_theme is defined) or (item.antigen_bundles is defined)
  with_items: '{{ users }}'

- name: install oh-my-zsh
  include_tasks: install-oh-my-zsh.yml
  when: antigen_install_oh_my_zsh
