---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-antigen-debian-min
    image: debian:8
  - name: ansible-role-antigen-debian-max
    image: debian:9
  - name: ansible-role-antigen-ubuntu-min
    image: ubuntu:14.04
  - name: ansible-role-antigen-ubuntu-max
    image: ubuntu:18.04
  - name: ansible-role-antigen-centos
    image: centos:7
  - name: ansible-role-antigen-fedora
    image: fedora:28
  - name: ansible-role-antigen-opensuse-leap
    image: opensuse:42.2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
