---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible_role_antigen_debian_min
    image: debian:8
  - name: ansible_role_antigen_debian_max
    image: debian:9
  - name: ansible_role_antigen_ubuntu_min
    image: ubuntu:14.04
  - name: ansible_role_antigen_ubuntu_max
    image: ubuntu:18.04
  - name: ansible_role_antigen_centos
    image: centos:7
  - name: ansible_role_antigen_fedora
    image: fedora:28
  - name: ansible_role_antigen_opensuse
    image: opensuse:42.2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
